
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonbarbosdev/front-syncdb:latest
    container_name: front-syncdb
    restart: on-failure
    ports:
      - 3000:4200
